server:
  port: 8081
spring:
  application:
    name: spring-boot-client-app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/SpringBootRealm
